/**
 * Sidebar configuration for the "О проекте" (About) section
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aboutSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
